### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cgserrant** [instanttim/MonitorMate#40]
How to set the ip address of the mate and port number in the config file ? also how to get the token? Sorry very new to this .

**Comment by instanttim** [comment]
There are two parts to the project, the python script which gets the Data Stream from the Mate3. It then cleans it up and reformats the data and sends it to your web server. 

I think you are looking in the configuration file for the Web Server (config.php). In the Data Stream Host directory you'll see the scripts to run on your local client. It doesn't need to know the IP address of your mate, just what port to listen on for the Data Stream, which is a command line argument. There's a shell script you can use to start it as a deamon on most Linux computers.

Note that on your Mate3 you do need to configure the destination IP address and Port to send the data stream, which again should be the local computer on which you're running the python scripts.

PS: this "issues" section on github is for filing bugs, not general conversation. Feel free to email me if you just need to ask questions or need help getting it up and running. I recognize it's not very user-friendly and it's rather technical... unfortunately.

**Comment by cgserrant** [comment]
Hi Timothy


Thanks for your reply and sorry for posting in issues.

Lets see if I can explain what I am trying to do. I have wattplot running
on a machine that is plugged directly into the mate via seral. As its a
mate2 and mate 3 is at outback again for repair. Now whattplot has a tcp
server running on it that spits out raw mate data (outback code) but needs
a telnet session to connect to it to get the data . Is there a way for me
to connect to that tcp data stream using the script? Also I am trying run
this all on windows machine running wamp.


Also new to this how do I change the listing port . Please give example .


Cheers
Chris

**Comment by jcheil** [comment]
Dump wattplot, that program is a joke. You can't have 2 programs listen on
the same port.
