### ISSUE TITLE
Display FRX inverter data

### ISSUE THREAD

**Issue by chinezbrun** [instanttim/MonitorMate#43]
inverter is not displayed in details tab - details.html -FXR specific code
gauges and charts are not updated for inverter (FXR) -> gauges.js, charts.js to include FXR specific code
offsetting mode are not display -> post_datastream.php - new operating mode should be added - FXR specific (code 14 - Offsetting)

**Comment by instanttim** [comment]
@chinezbrun submitted the pull request to fix this...
